jobs:
- job: Debug_Build
  pool: Hosted Ubuntu 1604
  steps:
    - template: templates/set-test-data-variables-step.yml
    - script: 'tools/ci_build/github/linux/server_run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -k $(acr.key) -x "--config Debug --build_server --use_openmp --use_full_protobuf --enable_server_tests"'
      displayName: 'Debug Build'
    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
    - template: templates/clean-agent-build-directory-step.yml
- job: Release_Build
  pool: Hosted Ubuntu 1604
  steps:
    - template: templates/set-test-data-variables-step.yml
    - script: 'tools/ci_build/github/linux/server_run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -k $(acr.key) -x "--config Release --build_server --use_openmp --use_full_protobuf --enable_server_tests"'
      displayName: 'Release Build'
    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
    - template: templates/clean-agent-build-directory-step.yml