jobs:
- job: Linux_CI_Dev
  pool: Linux-CPU
  steps:
    - script: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d cpu -r $(Build.BinariesDirectory) -x "--use_mklml"'
      displayName: 'Command Line Script'
      env:
        AZURE_BLOB_KEY: $(onnxruntime-storage-key)
    - script: 'sudo rm -rf $(Agent.BuildDirectory)'
      displayName: 'Clean build folders/files'
      condition: always()