jobs:
- job: Windows_CI_GPU_Dev
  pool: Win-GPU-CUDA10
  variables:
    CUDA_VERSION: '10.0'
  steps:
    - template: templates/set-test-data-variables-step.yml

    - task: CmdLine@1
      displayName: 'Download cmake'
      inputs:
        filename: python
        arguments: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\download_cmake.py --build_dir $(Build.BinariesDirectory)'

    - task: PowerShell@1
      displayName: 'Set CUDA path'
      inputs:
        scriptName: 'tools/ci_build/github/windows/set_cuda_path.ps1'
        arguments: '-CudaMsbuildPath C:\local\cudaMsbuildIntegration-10.0.130-win10 -CudaVersion $(CUDA_VERSION)'

    - task: BatchScript@1
      displayName: 'Setup VS2017 env vars'
      inputs:
        filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'
        arguments: 'amd64 -vcvars_ver=14.11'
        modifyEnvironment: true

    - task: BatchScript@1
      inputs:
        filename: build.bat
        arguments: ' --skip_submodule_sync --cmake_path $(Build.BinariesDirectory)\cmake\bin\cmake.exe --ctest_path $(Build.BinariesDirectory)\cmake\bin\ctest.exe --config Debug Release --enable_onnx_tests --test_data_url $(TestDataUrl) --test_data_checksum $(TestDataChecksum) --use_mkldnn --build_shared_lib --build_csharp --use_cuda --cuda_home="C:\local\cuda_10.0.130_win10" --cudnn_home="C:\local\cudnn-10.0-windows10-x64-v7.3.1.20\cuda"'
        workingFolder: "$(Build.SourcesDirectory)"

    - task: PowerShell@1
      displayName: 'Clean up CUDA props files'
      inputs:
        scriptName: 'tools/ci_build/github/windows/clean_up_cuda_prop_files.ps1'
        arguments: '-CudaVersion $(CUDA_VERSION)'

    - template: templates/clean-agent-build-directory-step.yml
